rvm:
  - 1.9.3
  - 2.0.0
  - 2.1

branches:
  only:
    - master


gemfile:
  - gemfiles/chef-11.12.0.gemfile
  - gemfiles/chef-11.14.0.gemfile
  - gemfiles/chef-master.gemfile

matrix:
  fast_finish: true
  allow_failures:
    - gemfile: gemfiles/chef-master.gemfile
